### ISSUE TITLE
Welcome Page

### ISSUE THREAD

**Issue by BerkayBideci** [hunctasci/capstone-template-team-3#12]
![Screenshot 2023-07-03 120138](https://github.com/hunctasci/capstone-template-team-3/assets/78705348/26280bc4-b37a-4da9-aaf6-fc121e7c5866)

Welcome Page should be implemented in the project. The "Start Today" button should redirect the user to the Navigation Page.

**Comment by sesamemaki** [comment]
welcomepage image should not be imported URL, image should be in public folder.
